import oracledb 
from datetime import datetime, timedelta

# Bağlantı bilgilerinizi buraya girin
db_config = {
    "user": "yztest",
    "password": "yztest",
    "dsn": "localhost:1521/DBAI"  # Host:Port/Servis_Adi (Örn: XE veya ORCL)
}

def create_db_and_tables():
    try:
        # Oracle bağlantısı
        conn = oracledb.connect(
            user=db_config["user"],
            password=db_config["password"],
            dsn=db_config["dsn"]
        )
        cursor = conn.cursor()

        # 1. Customers Tablosu (Identity Column ile otomatik ID)
        cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE orders';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
        """)
        
        cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE customers';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
        """)

        cursor.execute("""
        CREATE TABLE customers (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            first_name VARCHAR2(100) NOT NULL,
            last_name VARCHAR2(100) NOT NULL,
            pin VARCHAR2(10) NOT NULL
        )
        """)

        # 2. Orders Tablosu
        cursor.execute("""
        CREATE TABLE orders (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            customer_id NUMBER NOT NULL,
            order_date DATE NOT NULL,
            product_name VARCHAR2(200) NOT NULL,
            amount NUMBER(10, 2) NOT NULL,
            CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
        )
        """)

        # Veri Ekleme
        customers = [
            ("John", "Doe", "1234"),
            ("Jane", "Smith", "5678")
        ]
        # Oracle'da yer tutucu olarak :1, :2 kullanılır
        cursor.executemany("INSERT INTO customers (first_name, last_name, pin) VALUES (:1, :2, :3)", customers)

        # Müşteri ID'lerini al
        cursor.execute("SELECT id FROM customers ORDER BY id")
        customer_ids = [row[0] for row in cursor.fetchall()]

        orders = [
            (customer_ids[0], datetime.now() - timedelta(days=10), "Laptop", 1200.00),
            (customer_ids[0], datetime.now() - timedelta(days=45), "Mouse", 25.00),
            (customer_ids[1], datetime.now() - timedelta(days=5), "Keyboard", 75.00)
        ]
        cursor.executemany("INSERT INTO orders (customer_id, order_date, product_name, amount) VALUES (:1, :2, :3, :4)", orders)

        conn.commit()
        print("Oracle veritabanı tabloları oluşturuldu ve veriler eklendi.")

    except oracledb.Error as e:
        print(f"Hata oluştu: {e}")
    finally:
        if conn:
            conn.close()

if __name__ == "__main__":
    create_db_and_tables()